### ISSUE TITLE
图片标题在代码里面写死了，还有需要改造打开预览后的页面能否实现呢

### ISSUE THREAD

**Issue by LiJing890** [MarvenGong/vue2-viewer#1]

**Comment by MarvenGong** [comment]
马上处理，“改造打开预览后的页面”具体的需求是什么样的呢


------------------ 原始邮件 ------------------
发件人: "LiJing890"<notifications@github.com>;
发送时间: 2019年4月24日(星期三) 下午2:39
收件人: "MarvenGong/vue2-viewer"<vue2-viewer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [MarvenGong/vue2-viewer] 图片标题在代码里面写死了，还有需要改造打开预览后的页面能否实现呢 (#1)




Closed #1.
